### ISSUE TITLE
Password field during creation

### ISSUE THREAD

**Issue by SvenBuis** [vpsserver-com/whmcs-vpsserver-com#3]
Passwords can not be set during the creation of a server, field needs to be revoked.

**Comment by ukbssltd** [comment]
Certainly an issue. We did manage to get around this with a small change top code in the config product tpl.

**Comment by ukbssltd** [comment]
Langom also offers an option to disable it but it also disables hostname choice. Would not be an issue if you could actaully change it from the client area but it fails.

**Comment by ukbssltd** [comment]
We ficed this via a simple hook
