### ISSUE TITLE
WHMCS Addon Install

### ISSUE THREAD

**Issue by Dexxa1024** [vpsserver-com/whmcs-vpsserver-com#5]
Im adding the the token to my password in whmcs servers part, But since the whmcs updates its needing a hostname to install the addon 

Validation Error
The Hostname or IP Address format is invalid.

How do we fix this so whmcs can add the addon as a server?

**Comment by SvenBuis** [comment]
Hello,

Please follow all the steps provided in the manual. It also provides the data for the hostname.
